name: CI

on:
  push:
    branches: [ "main" ]   # change to master if needed
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Say hi
        run: echo "Build successful!"
